version: '3.5'

volumes:
  pgdata:

services:
  
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./deployments:/docker-entrypoint-initdb.db
      
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

  bot:
    depends_on:
      - db
    image: tggolangbot
    environment:
      CREATE_TABLE: "yes"
      DB_SWITCH: "on"
      TOKEN: ${TOKEN}
      API_CMC: ${API_CMC}
      HOST: db
      PORT: 5432
      USER: postgres
      PASSWORD: test
      DBNAME: postgres
      SSLMODE: disable
      LANGUAGE: en
    build:
      context: .
      dockerfile: ./Dockerfile.debug
    ports:
      - 12345:12345