version: '3.5'

volumes:
  pgdata:
  logs:
  
services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./deployments/:/docker-entrypoint-initdb.d/
      
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

  bot:
    depends_on:
      - db
    environment:
      CREATE_TABLE: "yes"
      DB_SWITCH: "on"
      TOKEN: ${TOKEN}
      API_CMC: ${API_CMC}
      HOST: db
      PORT: 5432
      USER: postgres
      PASSWORD: test
      DBNAME: postgres
      SSLMODE: disable
      LANGUAGE: en
      BOT_NAME: ${BOT_NAME}
    build:
      context: .
      dockerfile: ./Dockerfile
      labels:
        com.tg_golang_bot.name: "${BOT_NAME}"
        com.tg_golang_bot.version: "0.0.9.5"
    volumes:
      - logs:/logs/
    ports:
      - 3000:3000