version: '3.5'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

  bot:
    depends_on:
      - db
    image: tggolangbot
    environment:
      CREATE_TABLE: "yes"
      DB_SWITCH: "on"
      TOKEN: 7125415904:AAEy8G3UeKuLcABGT6Ouh_gWgp0JVPhetCY
      HOST: db
      PORT: 5432
      USER: postgres
      PASSWORD: test
      DBNAME: postgres
      SSLMODE: disable